<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>DuxCommunity.ChartEditor</RootNamespace>
    <!-- 本机只有 .NET 10 运行时也可启动这个 net9.0 桌面应用。 -->
    <RollForward>LatestMajor</RollForward>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.8" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.8" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.8" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\chart-editor-core\ChartEditor.Core.csproj" />
  </ItemGroup>
</Project>
